name: update_markdown

on:
  push:
    branches:
      - "feature/**"

jobs:
  multi-repos:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir tools
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: tools
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: lop9940/markdown_tools
          path: another
      # - run: |
      #     pwd
      #     ls -la
      # - name: Check the main repo
      #   working-directory: main
      #   run: |
      #     pwd
      #     ls -la
      # - name: Check the another repo
      #   working-directory: another
      #   run: |
      #     pwd
      #     ls -la