name: update_markdown

on:
  push:
    branches:
      - "feature/**"


jobs:
  link_correction_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: lop9940/markdown_tools
          path: tools
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Run correction_mermaid_link.py
        working-directory: main
        run: python ../tools/update_markdown/update_markdown/correction_mermaid_link.py "${{ github.repository }}" "${{ github.ref_name }}"
      - name: Run Git
        working-directory: main
        run: |
          git config --global user.name "lop9940"
          git config --global user.email "qaqclop9940@gmail.com"
          git add .
          git commit -m "Update by GitHub Action run:correction_mermaid_link.py"
          git push
      - name: Run check_mermaid_link.py
        working-directory: main
        run: |
          python ../tools/update_markdown/update_markdown/check_mermaid_link.py
      - name: Run Git
        working-directory: main
        run: |
          git config --global user.name "lop9940"
          git config --global user.email "qaqclop9940@gmail.com"
          git add .
          git commit -m "Update by GitHub Action run:check_mermaid_link.py"
          git push